services:
  postgres:
    profiles:
      - dev-only

  api:
    build:
      target: prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    command: sh -c "bunx prisma migrate deploy && node dist/main.js"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    networks:
      default:
      gateway:
        aliases:
          - ilmarinen-api

  web:
    build:
      target: prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    networks:
      default:
      gateway:
        aliases:
          - ilmarinen-web

networks:
  gateway:
    external: true
    name: muntim_gateway
